### PR TITLE
feat dropdown: add a direction option allowing dropup menus

### PR DESCRIPTION
**Pull request by ThomasCrvsr**

### CODE REVIEW

**Comment by malexandre** [comment]
Hi!

First, thanks for the contribution. It's something really useful.
Could you remove the dist folder from your commits? We are thinking about a way to include it in the repo, but for now we'll keep it updated only for the releases. And we want the commit to be easy to read, and having all the dist in your feature's commit makes it harder to find the feature's code.

I'll test this as soon as I can, but the first question in my head is how your feature plays with "from-top" parameter? I'll reply again after my tests.

**Comment by malexandre** [comment]
It plays quite nicely with the "from-top", but the animation isn't as smooth with it. But for now I think it will be enough. When we'll have time, the goal is to make the animation really feeling to come from the click, and opening at the best position regarding the current cursor position on the page. So the up/down choice will be automatic, and the animation reworked. But for now our solution is basic, and with yours, it becomes more powerful.

I'll rune this with the CSS team, and if they're ok, I'll merge your PR once you'll have removed the dist folder.

**Comment by ThomasCrvsr** [comment]
Okay, no problem. I'll do it tonight.
I see what you mean with the position of the cursor, but will you keep a way to force the behaviour ?

Not related with this specific issue, but is there a particular way to discuss with the team (others than GH issues) ? I'd be glad to help, but I don't now which parts of the Roadmap are already in progress and on which points I can focus on ^^

**Comment by malexandre** [comment]
We might keep a way to force the behaviour. Just by curiosity, can you describe me a case when you'd want to force it? I'm not sure I can think of one once you know that it will always chose the best regarding the current position in the window. And regarding the spec, it must be "centered" ([video](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWcF9Ndmt1RTZoWk0/components-menus-usage-061001_Textfield_Dropdown_xhdpi_003.mp4) from [the official spec](http://www.google.fr/design/spec/components/menus.html#menus-usage)).

And to discuss with us, for now it will be via Twitter. I'm [@thagou](https://twitter.com/thagou), and we have the company account [@lumapps](https://twitter.com/lumapps). There is also our G+ accounts ([me](https://plus.google.com/u/0/112017292931075994945/posts) or [the company](https://plus.google.com/u/0/+LumApps)). For both the company accounts, I'm not sure who is watching them. I know someone is, but not someone directly from lumX I think.

**Comment by ThomasCrvsr** [comment]
Oh I see, I read too quickly your last post. Yep, no need to force anything ^^

**Comment by ThomasCrvsr** [comment]
I've deleted the dist folder. Let me know if it's okay !

**Comment by malexandre** [comment]
I meant delete the diff forlders update from your commit ^^. Just keep the code for your feature.

**Comment by ThomasCrvsr** [comment]
It's hard on Monday ^^' Normally everything is ok this time.

**Comment by malexandre** [comment]
Perfect, it's merged!

**Pull request merged**
