### PR TITLE
fix select: add another missing wrapper

### PR DESCRIPTION
**Pull request by clementprevot**

### CODE REVIEW

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing your PR. Thank you!

**Comment by FernandoFranco** [comment]
Hi, I'm using v1.0.0rc2 by bower, however this problem persists

**Comment by malexandre** [comment]
What is the problem? It was a PR, not a bug.

**Comment by FernandoFranco** [comment]
Select cause error on the console, and does not render

```
Error: [$injector:unpr] http://errors.angularjs.org/1.5.0/$injector/unpr?p0=eProvider%20%3C-%20e
    at Error (native)
    at http://localhost:3000/bower_components/angular/angular.min.js:6:416
    at http://localhost:3000/bower_components/angular/angular.min.js:43:7
    at Object.d [as get] (http://localhost:3000/bower_components/angular/angular.min.js:40:270)
    at http://localhost:3000/bower_components/angular/angular.min.js:43:69
    at d (http://localhost:3000/bower_components/angular/angular.min.js:40:270)
    at e (http://localhost:3000/bower_components/angular/angular.min.js:41:1)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.min.js:41:86)
    at T.instance (http://localhost:3000/bower_components/angular/angular.min.js:86:444)
    at u (http://localhost:3000/bower_components/angular/angular.min.js:65:338)
```

**Comment by FernandoFranco** [comment]
Hi, i receive the 'Error: [$injector:unpr]' only in /dist/lumx.min.js, in /dist/lumx.js the executing is perfect

**Pull request closed without merging**
