### PR TITLE
Adding a variable to specify the date format used by controller.

### PR DESCRIPTION
**Pull request by daniel-oliveiravas**

### CODE REVIEW

**Comment by malexandre** [comment]
Hi! Can you remove the commit with the dist folder and rework your first commit message according to the contributing guidelines please?

**Comment by daniel-oliveiravas** [comment]
Dist folder removed and commit message changed.

**Comment by felansu** [comment]
Great work @daniel-oliveiravas !

**Comment by malexandre** [comment]
Ok, now it's easier to look the code, thanks! There is a little problem, the format is not dynamic. It will only use the one set at init. The easier way to fix this is to always use $scope.dateFormat inside the directive instead of re-assigning to the var dateFormat. And doing that, you need to make sure that it's always initialised, so add a test in the init or link function (like in [the search field](https://github.com/lumapps/lumX/blob/master/modules/search-filter/js/search-filter_directive.js#L27)).

And could you change your "if" line 18 to be in Allman style while you're doing that? (meaning the brace must be on a new line)

Thanks a lot for the PR!

**Comment by matmkian** [comment]
We've just released LumX v1.0.0rc1. This new version add the option, so I'm closing your PR. Thank you!

**Pull request closed without merging**
